### ISSUE TITLE
suggestion: add `title` attribute to truncated links

### ISSUE THREAD

**Issue by zacanger** [govtrack/govtrack.us-web#321]
[Example here](https://github.com/govtrack/govtrack.us-web/blob/5a08a45eb641bc29a342baddb48d147f022975e6/templates/bill/bills_overview.html#L132). This would allow a user to hover/long-press on a link to see the full text of a truncated bill title, rather than having to open the page.

**Comment by JoshData** [comment]
Great idea! I've tried to do that comprehensively throughout the site. Unfortunately some of the truncation comes from a character limit in some of the database tables (this appears as truncation without "..." at the end), so not all cases are fixed by this. But it's an improvement. Fixing the database is harder because it's a little tricky and time consuming to re-load data from disk.

**Comment by zacanger** [comment]
Ah, looks like it's using a CharField/varchar in the models, so maxlen of 255? And (I didn't check this out before) it looks like data gets loaded in at migration or spin-up time? I see why that's a problem. An A/B deployment would definitely help but that may be beyond the resources you have available right now. Thanks for the response!
